production:
 host: 127.0.0.1
 adapter: postgresql
 #encoding: unicode
 encoding: utf8
 database: moveco_production
 pool: 5
 username: deploy
 password: deploy
 timeout: 5000
 
staging:
 host: 127.0.0.1
 adapter: postgresql
 #encoding: unicode
 encoding: utf8
 database: moveco_staging
 pool: 5
 username: deploy
 password: deploy
 timeout: 5000

development:
 host: 127.0.0.1
 adapter: postgresql
 #encoding: unicode
 encoding: utf8
 database: moveco_development
 pool: 5
 username: deploy
 password: deploy
 timeout: 5000
