development: &default
  mode: sandbox
  client_id: AWS7CvetykFV9EQEwY0bnU9t31tagl9t7-xfRX2U1SkD76r0--HmHp6WhXCoEsq7QbDZKYETym7yybTY
  client_secret: EAJ7C6vUlH-Q6N8TzZxjBUeLUavmR8GAy4RbIYmTrYZKKEwa0XjksC2HuSDENbqv5nqnR0bxDftut5cJ
  # # with Proxy
  # http_proxy: http://proxy-ipaddress:3129/
  # # with CA File
  # ssl_options:
  #   ca_file: config/cacert.pem
  # # Override Endpoint
  # rest_endpoint: https://api.sandbox.paypal.com
test:
  <<: *default
production:
  mode: live
  client_id: AQN_fBisTB76iBtCIR3gJ2Z1HI6tVYpTDJoBQKmGKvkQA2LlPrnopb7iKyqRSjD3Y5nF-2Q1fZ822eyr
  client_secret: ED_9IDwb7KF_q2_TaNX6yZTerSchO71PlMO96CRr4JfQEXxAY0pebuDuFXgOwx8uV3gEAcFbNOnVivEb
